/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    HelloWorld: typeof import('./components/common/hello-world.vue')['default']
    IconCommunity: typeof import('./components/icons/icon-community.vue')['default']
    IconDocumentation: typeof import('./components/icons/icon-documentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/icon-ecosystem.vue')['default']
    IconSupport: typeof import('./components/icons/icon-support.vue')['default']
    IconTooling: typeof import('./components/icons/icon-tooling.vue')['default']
    InfiniteScroll: typeof import('./components/common/infinite-scroll.vue')['default']
    NewsBox: typeof import('./components/news/news-box.vue')['default']
    PravicyAgree: typeof import('./components/common/pravicy-agree.vue')['default']
    PrivacyAgree: typeof import('./components/common/privacy-agree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
