/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthError: typeof import('./components/auth/auth-error.vue')['default']
    AuthLogin: typeof import('./components/auth/auth-login.vue')['default']
    AuthNonLoggedBox: typeof import('./components/auth/auth-non-logged-box.vue')['default']
    AuthRegister: typeof import('./components/auth/auth-register.vue')['default']
    AuthUnloggedBox: typeof import('./components/auth/auth-unlogged-box.vue')['default']
    AuthView: typeof import('./components/auth/auth-view.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./components/common/hello-world.vue')['default']
    IEpHelpFilled: typeof import('~icons/ep/help-filled')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IEpHouse: typeof import('~icons/ep/house')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpTrendCharts: typeof import('~icons/ep/trend-charts')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    NewsBox: typeof import('./components/news/news-box.vue')['default']
    NsasBox: typeof import('./components/common/nsas-box.vue')['default']
    NsasCountdown: typeof import('./components/miscellaneous/nsas-countdown.vue')['default']
    NsasDialog: typeof import('./components/common/nsas-dialog.vue')['default']
    NsasMenu: typeof import('./components/common/nsas-menu.vue')['default']
    NsasPrivacyAgree: typeof import('./components/miscellaneous/nsas-privacy-agree.vue')['default']
    NsasStarlink: typeof import('./components/common/nsas-starlink.vue')['default']
    NsasStarLink: typeof import('./components/common/nsas-star-link.vue')['default']
    NsasWelcome: typeof import('./components/miscellaneous/nsas-welcome.vue')['default']
    PrivacyAgree: typeof import('./components/miscellaneous/privacy-agree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarLink: typeof import('./components/miscellaneous/star-link.vue')['default']
    TimeCountdown: typeof import('./components/miscellaneous/time-countdown.vue')['default']
    WelcomeInfo: typeof import('./components/miscellaneous/welcome-info.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
