/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./components/common/hello-world.vue')['default']
    IEpHelpFilled: typeof import('~icons/ep/help-filled')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IEpHouse: typeof import('~icons/ep/house')['default']
    IEpTrendCharts: typeof import('~icons/ep/trend-charts')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    NewsBox: typeof import('./components/news/news-box.vue')['default']
    NsasBox: typeof import('./components/common/nsas-box.vue')['default']
    NsasCountdown: typeof import('./components/common/nsas-countdown.vue')['default']
    NsasMenu: typeof import('./components/common/nsas-menu.vue')['default']
    NsasPrivacyAgree: typeof import('./components/common/nsas-privacy-agree.vue')['default']
    NsasStarlink: typeof import('./components/common/nsas-starlink.vue')['default']
    NsasStarLink: typeof import('./components/common/nsas-star-link.vue')['default']
    NsasWelcome: typeof import('./components/common/nsas-welcome.vue')['default']
    PrivacyAgree: typeof import('./components/common/privacy-agree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
