name: Initialize

on:
  push:
    tags:
      - 'init-*'
  workflow_dispatch:

jobs:
  Docker_Image_Generate:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.1.1

      - name: Node Install
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '20.11.0'

      - name: Docker Image Push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag ${{ secrets.DOCKER_REPOSITORY }} ${{ secrets.DOCKER_REPOSITORY }}:$(date +%s)
          docker build . --no-cache --file Dockerfile
          docker push ${{ secrets.DOCKER_REPOSITORY }}:$(date +%s)

  Jenkins_Deploy:
    needs: Docker_Image_Generate
    runs-on: ubuntu-latest
    steps:
      - name: Send Trigger
        run: |
          response=$(curl -o /dev/null -s -w "%{http_code}\n" -u ${{ secrets.JENKINS_AUTH }} -X POST "https://${{ secrets.JENKINS_REPOSITORY }}/buildWithParameters?image=${{ secrets.DOCKER_REPOSITORY }}:latest")
          if [ "$response" -eq 201 ]; then
            echo "Build triggered successfully."
          else
            echo "Failed to trigger build. HTTP Status: $response"
            exit 1
          fi
